# Generated by Django 5.1.6 on 2025-02-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_is_2fa_verified_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='temp_login',
            field=models.BooleanField(default=False),
        ),
    ]
