# Generated by Django 5.1.6 on 2025-02-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customuser_temp_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='qr_code_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
