# Generated by Django 5.1.6 on 2025-02-12 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_customuser_qr_code_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='qr_code_url',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
