"""
Django settings for SSR_DjangoProject project.

Generated by 'django-admin startproject' using Django 3.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

SSL_CERT_FILE = "/etc/ssl/django/django.pem"
os.environ["REQUESTS_CA_BUNDLE"] = SSL_CERT_FILE

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1ctn6hxwve)$_=3=j1n^^ejxcq9&k93n)tghfq$#((srats3f%'
DOMAIN = os.environ.get("DOMAIN", "localhost") #ない場合はlocalhost
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", False)

ALLOWED_HOSTS = ["django",'localhost', DOMAIN, "innerproxy"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.staticfiles',  # 静的ファイルの管理に必要
    'django.contrib.auth',  # テンプレートコンテキストプロセッサで使われている
    'django.contrib.contenttypes',  # Django の認証システムに必要
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



ROOT_URLCONF = 'SSR_DjangoProject.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",  # 追加
                "django.contrib.messages.context_processors.messages",  # 追加
            ],
        },
    },
]

WSGI_APPLICATION = 'SSR_DjangoProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': None,  # 明示的にデータベースを無効化
    }
}



# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/


# STATIC_URL = f"https://{DOMAIN}/static/"
# MEDIA_URL = f"https://{DOMAIN}/media/"
# STATICFILES_DIRS = [] 
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

CERT_PATH = "/etc/ssl/certs/rootCA/custom-ca-bundle.crt"
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
