# Generated by Django 4.2 on 2025-02-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(unique=True)),
                ('is_2fa_enabled', models.BooleanField(default=False)),
                ('secret_key', models.CharField(blank=True, max_length=255, null=True)),
                ('is_verified_once', models.BooleanField(default=False)),
            ],
        ),
    ]
