# Generated by Django 4.2 on 2025-02-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwoFAServiceProject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('device_name', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('last_login', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='twofactorauth',
            name='is_verified_once',
        ),
        migrations.AddField(
            model_name='twofactorauth',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
    ]
